[rules]
blank = "ignore"
crooked = "ignore"
demo = "warn"
dev = "ignore"
fake = "warn"
githubs = "ignore"
heroku = "ignore"
mail = "ignore"
md5 = "ignore"
password = "warn"
private = "warn"
secret = "warn"
token = "warn"
pwd = "warn"
passwd = "warn"

[allowlist]
  description = "Allowlisted patterns for UMS"
  regexes = [
    "^http://localhost:*",
    "^https://github.com/beyondnetcode/evolith",
    "^https://github.com/beyondnetcode/ums"
  ]