/**
 * system-suites.mock.ts — Mock data matching AuthorizationDevDataSeeder exactly
 *
 * IDs are generated dynamically to match the actual database seed values.
 * Covers all CRUD scenarios: Active/Maintenance/Deprecated states,
 * full module→menu→submenu→option hierarchies, domain resources.
 */
import type { SystemSuite, SystemSuiteDomainResource } from '@domain/authorization/models/system-suite.model';

// ── Constants matching CoreDevDataSeeder ────────────────────────────────────
const RANSA_TENANT_ID = '3fa85f64-5717-4562-b3fc-2c963f66afa6';

// Note: IDs below are placeholders. The actual IDs are generated by the domain
// aggregates at seed time. The frontend should rely on the GraphQL response,
// not hardcoded IDs. These mocks are primarily for unit tests and Storybook.

// ── Suite 1: LOGISTICS_CORE ──────────────────────────────────────────────────
const logisticsCoreModules = [
  {
    id: 'sec-module-id',
    code: 'SEC',
    name: 'Security & Auditing',
    description: 'Security, user management, and audit trailing modules',
    status: 'Active',
    sortOrder: 1,
    menus: [
      {
        id: 'users-menu-id',
        code: 'USERS',
        label: 'Users Administration',
        description: 'Manage user accounts and details',
        sortOrder: 1,
        subMenus: [
          {
            id: 'list-submenu-id',
            code: 'LIST',
            label: 'User Directory',
            description: 'View and search all user accounts',
            sortOrder: 1,
            options: [
              { id: 'view-users-opt-id', code: 'VIEW_USERS', label: 'View Users List', description: 'Permission to view the users list', actionCode: 'VIEW', sortOrder: 1 },
              { id: 'edit-users-opt-id', code: 'EDIT_USERS', label: 'Edit User Profiles', description: 'Permission to edit and modify user profiles', actionCode: 'MANAGE', sortOrder: 2 },
            ],
          },
          {
            id: 'roles-submenu-id',
            code: 'ROLES',
            label: 'Roles & Permissions',
            description: 'Manage access control roles and templates',
            sortOrder: 2,
            options: [
              { id: 'view-roles-opt-id', code: 'VIEW_ROLES', label: 'View Security Roles', description: 'Permission to view roles in system', actionCode: 'VIEW', sortOrder: 1 },
              { id: 'manage-roles-opt-id', code: 'MANAGE_ROLES', label: 'Configure Permissions', description: 'Permission to edit access rights', actionCode: 'MANAGE', sortOrder: 2 },
            ],
          },
        ],
      },
      {
        id: 'audit-menu-id',
        code: 'AUDIT',
        label: 'Audit Trails',
        description: 'System operations logging and analysis',
        sortOrder: 2,
        subMenus: [
          {
            id: 'logs-submenu-id',
            code: 'LOGS',
            label: 'System Logs',
            description: 'View system telemetry and user transactions',
            sortOrder: 1,
            options: [
              { id: 'view-logs-opt-id', code: 'VIEW_LOGS', label: 'Search Audit Trail', description: 'Permission to query audit logs', actionCode: 'VIEW', sortOrder: 1 },
              { id: 'purge-logs-opt-id', code: 'PURGE_LOGS', label: 'Purge Historical Data', description: 'Permission to clear obsolete log records', actionCode: 'APPROVE', sortOrder: 2 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'config-module-id',
    code: 'CONFIG',
    name: 'System Configuration',
    description: 'Global properties, settings and email setup',
    status: 'Active',
    sortOrder: 2,
    menus: [
      {
        id: 'settings-menu-id',
        code: 'SETTINGS',
        label: 'Global Setup',
        description: 'Configure global system variables',
        sortOrder: 1,
        subMenus: [
          {
            id: 'params-submenu-id',
            code: 'PARAMS',
            label: 'App Parameters',
            description: 'Configure timeouts, thresholds and limits',
            sortOrder: 1,
            options: [
              { id: 'view-params-opt-id', code: 'VIEW_PARAMS', label: 'View Parameters', description: 'Permission to view system options', actionCode: 'VIEW', sortOrder: 1 },
              { id: 'edit-params-opt-id', code: 'EDIT_PARAMS', label: 'Update Global Config', description: 'Permission to edit critical global values', actionCode: 'MANAGE', sortOrder: 2 },
            ],
          },
          {
            id: 'smtp-submenu-id',
            code: 'SMTP',
            label: 'SMTP Server Setup',
            description: 'Email gateway and server connection',
            sortOrder: 2,
            options: [
              { id: 'test-smtp-opt-id', code: 'TEST_SMTP', label: 'Test SMTP Gateway', description: 'Permission to trigger email delivery test', actionCode: 'APPROVE', sortOrder: 1 },
            ],
          },
        ],
      },
    ],
  },
];

const logisticsCoreActions = [
  { id: 'view-action-id', code: 'VIEW', name: 'View Logistics Core' },
  { id: 'manage-action-id', code: 'MANAGE', name: 'Manage Logistics Core' },
  { id: 'approve-action-id', code: 'APPROVE', name: 'Approve Operations' },
  { id: 'create-action-id', code: 'CREATE', name: 'Create Record' },
  { id: 'read-action-id', code: 'READ', name: 'Read Record' },
  { id: 'update-action-id', code: 'UPDATE', name: 'Update Record' },
  { id: 'delete-action-id', code: 'DELETE', name: 'Delete Record' },
  { id: 'search-action-id', code: 'SEARCH', name: 'Search Records' },
];

const logisticsCoreDomainResources: SystemSuiteDomainResource[] = [
  { id: 'users-agg-id', type: 'Aggregate', code: 'USERS', name: 'Users Aggregate', description: 'User Management', moduleId: null },
  { id: 'inventory-agg-id', type: 'Aggregate', code: 'INVENTORY', name: 'Inventory Aggregate', description: 'Inventory Management', moduleId: null },
  { id: 'audit-log-ent-id', type: 'Entity', code: 'AUDIT_LOG', name: 'Audit Log Entity', description: 'Audit Logs', moduleId: null },
  { id: 'stock-level-ent-id', type: 'Entity', code: 'STOCK_LEVEL', name: 'Stock Level Entity', description: 'Stock Levels', moduleId: null },
];

// ── Suite 2: WMS ────────────────────────────────────────────────────────────
const wmsModules = [
  {
    id: 'inv-module-id',
    code: 'INV',
    name: 'Inventory Control',
    description: 'Inventory management and levels',
    status: 'Active',
    sortOrder: 1,
    menus: [
      {
        id: 'stock-menu-id',
        code: 'STOCK',
        label: 'Stock Administration',
        description: 'Stock levels and status',
        sortOrder: 1,
        subMenus: [
          {
            id: 'levels-submenu-id',
            code: 'LEVELS',
            label: 'Real-time Levels',
            description: 'Current physical stock status',
            sortOrder: 1,
            options: [
              { id: 'view-stock-opt-id', code: 'VIEW_STOCK', label: 'View Stock Levels', description: 'Permission to view real-time inventory counts', actionCode: 'INVENTORY_VIEW', sortOrder: 1 },
              { id: 'adjust-stock-opt-id', code: 'ADJUST_STOCK', label: 'Adjust Inventory Counts', description: 'Permission to perform physical inventory adjustments', actionCode: 'INVENTORY_EDIT', sortOrder: 2 },
            ],
          },
        ],
      },
      {
        id: 'ops-menu-id',
        code: 'OPS',
        label: 'Warehouse Operations',
        description: 'Stock movements and transfers',
        sortOrder: 2,
        subMenus: [
          {
            id: 'transfers-submenu-id',
            code: 'TRANSFERS',
            label: 'Warehouse Transfers',
            description: 'Move stock between physical locations',
            sortOrder: 1,
            options: [
              { id: 'initiate-transfer-opt-id', code: 'INITIATE_TRANSFER', label: 'Initiate Stock Transfer', description: 'Permission to draft and start a transfer request', actionCode: 'INVENTORY_EDIT', sortOrder: 1 },
              { id: 'approve-transfer-opt-id', code: 'APPROVE_TRANSFER', label: 'Approve Location Transfer', description: 'Permission to authorize inventory relocation', actionCode: 'INVENTORY_EDIT', sortOrder: 2 },
            ],
          },
        ],
      },
    ],
  },
];

const wmsActions = [
  { id: 'inv-view-action-id', code: 'INVENTORY_VIEW', name: 'View Inventory' },
  { id: 'inv-edit-action-id', code: 'INVENTORY_EDIT', name: 'Edit Inventory' },
];

const wmsDomainResources: SystemSuiteDomainResource[] = [];

// ── Exported mock array ──────────────────────────────────────────────────────
export const mockSystemSuites: SystemSuite[] = [
  {
    systemSuiteId: 'logistics-core-id',
    tenantId: RANSA_TENANT_ID,
    code: 'LOGISTICS_CORE',
    name: 'Logistics Core',
    description: 'Core operations and user management',
    status: 'Active',
    modules: logisticsCoreModules,
    actions: logisticsCoreActions,
    domainResources: logisticsCoreDomainResources,
  },
  {
    systemSuiteId: 'wms-id',
    tenantId: RANSA_TENANT_ID,
    code: 'WMS',
    name: 'Warehouse Management',
    description: 'Warehouse inventory management',
    status: 'Active',
    modules: wmsModules,
    actions: wmsActions,
    domainResources: wmsDomainResources,
  },
];
