global using Ums.Domain.Kernel;
global using Ums.Domain.Enums;
global using Ums.Domain.Events;
global using Ums.Shell.Ddd;
global using Ums.Domain.Kernel.ValueObjects;
global using Ums.Shell.Ddd.Interfaces;
global using Ums.Shell.Ddd.Services.Impl;
global using Ums.Shell.Ddd.Rules.Interfaces;
global using Ums.Shell.Ddd.Rules.Impl;
global using Ums.Shell.Ddd.ValueObjects.Common;
global using Ums.Shell.Ddd.ValueObjects.Audit;
global using Ums.Shell.Ddd.Rules;
global using Ums.Domain.Approvals.ValueObjects;

global using Ums.Domain.Approvals.Rules;
global using Ums.Domain.Authorization.ValueObjects;
global using Ums.Domain.Iga.ValueObjects;
global using Ums.Domain.Identity.ValueObjects;
global using Ums.Domain.Compliance.ValueObjects;
global using TenantIdVO = Ums.Domain.Kernel.ValueObjects.TenantId;
global using UserIdVO = Ums.Domain.Kernel.ValueObjects.UserId;
global using OrganizationIdVO = Ums.Domain.Kernel.ValueObjects.OrganizationId;
global using RequestTypeVO = Ums.Domain.Approvals.ValueObjects.RequestType;
global using RequiredApprovalsVO = Ums.Domain.Approvals.ValueObjects.RequiredApprovals;
global using JustificationVO = Ums.Domain.Kernel.ValueObjects.Justification;
global using CommentVO = Ums.Domain.Kernel.ValueObjects.Comment;
global using WorkflowIdVO = Ums.Domain.Approvals.ValueObjects.WorkflowId;
global using VersionVO = Ums.Domain.Kernel.ValueObjects.Version;
global using NameVO = Ums.Domain.Kernel.ValueObjects.Name;
global using DescriptionVO = Ums.Domain.Kernel.ValueObjects.Description;
global using CodeVO = Ums.Domain.Kernel.ValueObjects.Code;
