-- UMS - Mandatory Parametric Catalog Standard
-- Date: 2026-05-14
-- Scope: SQL Server 2022
-- Applies mandatory Code/Value/Description + scope uniqueness to
-- APP_CONFIGURATION, APPROVAL_WORKFLOW, NOTIFICATION_RULE, ACCESS_ENFORCEMENT_POLICY.

/* APP_CONFIGURATION */
ALTER TABLE [ums_config].[APP_CONFIGURATION]
ADD
    [Code] NVARCHAR(100) NOT NULL,
    [Value] NVARCHAR(MAX) NOT NULL,
    [Description] NVARCHAR(MAX) NOT NULL;

CREATE UNIQUE INDEX [UX_APP_CONFIGURATION_CODE_SCOPE]
ON [ums_config].[APP_CONFIGURATION] (
    [Code],
    ISNULL([TenantId], '00000000-0000-0000-0000-000000000000'),
    ISNULL([SuiteId], '00000000-0000-0000-0000-000000000000'),
    ISNULL([ModuleId], '00000000-0000-0000-0000-000000000000')
);

/* APPROVAL_WORKFLOW */
ALTER TABLE [ums_approval].[APPROVAL_WORKFLOW]
ADD
    [Code] NVARCHAR(100) NOT NULL,
    [Value] NVARCHAR(MAX) NOT NULL,
    [Description] NVARCHAR(MAX) NOT NULL;

CREATE UNIQUE INDEX [UX_APPROVAL_WORKFLOW_CODE_SCOPE]
ON [ums_approval].[APPROVAL_WORKFLOW] (
    [Code],
    [TenantId],
    ISNULL([SuiteId], '00000000-0000-0000-0000-000000000000')
);

/* NOTIFICATION_RULE */
ALTER TABLE [ums_compliance].[NOTIFICATION_RULE]
ADD
    [Code] NVARCHAR(100) NOT NULL,
    [Value] NVARCHAR(MAX) NOT NULL,
    [Description] NVARCHAR(MAX) NOT NULL;

CREATE UNIQUE INDEX [UX_NOTIFICATION_RULE_CODE_SCOPE]
ON [ums_compliance].[NOTIFICATION_RULE] ([Code], [TenantId], [DocumentTypeId]);

/* ACCESS_ENFORCEMENT_POLICY */
ALTER TABLE [ums_compliance].[ACCESS_ENFORCEMENT_POLICY]
ADD
    [TenantId] UNIQUEIDENTIFIER NULL,
    [Code] NVARCHAR(100) NOT NULL,
    [Value] NVARCHAR(MAX) NOT NULL,
    [Description] NVARCHAR(MAX) NOT NULL;

CREATE UNIQUE INDEX [UX_ACCESS_ENFORCEMENT_POLICY_CODE_SCOPE]
ON [ums_compliance].[ACCESS_ENFORCEMENT_POLICY] (
    [Code],
    ISNULL([TenantId], '00000000-0000-0000-0000-000000000000'),
    [DocumentTypeId]
);

-- NOTE:
-- For production rollout, this script must be split into
-- 1) Backfill (populate Code/Value/Description),
-- 2) NOT NULL enforcement,
-- 3) Unique indexes activation.
