global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.Extensions.DependencyInjection;
global using Ums.Domain.Kernel;
global using Ums.Domain.Identity;
global using Ums.Application.Common.Interfaces;
